# Generated by Django 4.2.16 on 2024-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='Ingredients',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Instructions',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/'),
        ),
    ]
