# Generated by Django 4.2.16 on 2024-10-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_recipes_ingredients_recipes_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Instructions',
            field=models.TextField(null=True),
        ),
    ]
