# Generated by Django 4.2.16 on 2024-10-07 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_alter_recipes_ingredients_alter_recipes_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='Prep_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
